Update vet clinic
luccamicale/vet_clinic pull request #2
Opened 2022-12-13 23:17 UTC by luccamicale

## Update Vet Clinic Database 💯 

##https://github.com/luccamicale/vet_clinic 🔢 

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I used the update
- [ ] I used the delete
- [ ] I used the custom queries 🥇 💯 👍 

![DATA3](https://user-images.githubusercontent.com/107897361/207465705-66018161-20bb-4d3b-9982-b6cf0b6da7f1.PNG)
![DATA4](https://user-images.githubusercontent.com/107897361/207465727-2f7aa0ef-4ab3-40b2-857e-53fdd2d84dda.PNG)
![DATA5](https://user-images.githubusercontent.com/107897361/207465744-97e2546c-7a90-402d-8cef-ffa8c6041b56.PNG)
![DATA6](https://user-images.githubusercontent.com/107897361/207465749-6ed3bb02-d579-43e3-a9aa-ea4b9f4b0448.PNG)
![COSTUM QUERYS](https://user-images.githubusercontent.com/107897361/207465761-71591896-71a7-42eb-88b2-9bbb1ec87a4d.PNG)

2022-12-13 23:43 UTC, zieeco requested changes
Hi @luccamicale ,


Great job so far! 👏 
You've done it well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice querry. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._


<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions
- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-13 23:43 UTC, zieeco commented on schema.sql
> +    species VARCHAR
- Hey, please, let's specify the numbers of characters the column can take to help maintain our database to improve its performance. Not specifying means the column can take any number of characters and this is not ideal for your database. eg `varchar(100);`

2022-12-13 23:43 UTC, zieeco commented on data.sql
> +INSERT INTO animals (name, date_of_birth, escape_attempts, neutered, weight_kg) VALUES ('Charmander', 'Febrary 8, 2020', 0, false, 11);
- Hey, please, let's kindly enure we pass the correct value for the datatype to help reduce issues one could face with not sending the correct data to the correct datatype in the database. The value for the weight should be a floating number as it is a decimal and not an integer. Kindly update the 11 to `-11.0`

2022-12-13 23:43 UTC, zieeco commented on data.sql
> +INSERT INTO animals (name, date_of_birth, escape_attempts, neutered, weight_kg) VALUES ('Plantmon', 'November 15, 2021', 2, true, 5.7);
- Hey, please, kindly ensure you've sent the correct value to the database as this should be `-5.7`

2022-12-13 23:43 UTC, zieeco commented on data.sql
> +INSERT INTO animals (name, date_of_birth, escape_attempts, neutered, weight_kg) VALUES ('Squirtle', 'April 2, 1993', 3, false, 12.13);
- Hey, please, kindly ensure you've sent the correct value to the database as this should be `-12.13`

2022-12-13 23:43 UTC, zieeco commented on data.sql
> +INSERT INTO animals (name, date_of_birth, escape_attempts, neutered, weight_kg) VALUES ('Angemon', 'June 12, 2005', 1, true, 45);
- Hey, please, kindly ensure you've sent the correct value to the database as this should be `-45.0`

2022-12-13 23:43 UTC, zieeco commented on data.sql
> +INSERT INTO animals (name, date_of_birth, escape_attempts, neutered, weight_kg) VALUES ('Blossom', 'October 13, 1998', 3, true, 17);
- Hey, please, let's kindly ensure we pass the correct value for the datatype to help reduce issues one could face with not sending the correct data to the correct datatype in the database. The value for the weight should be a floating number as it is a decimal and not an integer. Kindly update the 11 to `17.0`

2022-12-13 23:43 UTC, zieeco commented on data.sql
> +INSERT INTO animals (name, date_of_birth, escape_attempts, neutered, weight_kg) VALUES ('Ditto', 'May 14, 2022', 4, true, 22);
- Hey, please, let's kindly enure we pass the correct value for the datatype to help reduce issues one could face with not sending the correct data to the correct datatype in the database. The value for the weight should be a floating number as it is a decimal and not an integer. Kindly update the 11 to `22.0`

2022-12-13 23:43 UTC, zieeco commented on schema.sql
> +    species VARCHAR
#### README FILE

- Hey, great job adding the readme file, however, let's kindly update our readme to the current readme [template](https://github.com/microverseinc/readme-template) to conform to the new structure and be consistent to make our readme more professional.

2022-12-14 01:34 UTC, luccamicale commented
I modified the problem with the data.sql. Now My project is complete and should be approved!!! 💯 
![Uploading INSERT.PNG…]()

2022-12-14 01:34 UTC, luccamicale commented
and i added the professional Readme

2022-12-14 02:00 UTC, Reem-lab approved these changes
# Hi @luccamicale 👋🏻👋🏻 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉🚀🔥🎉🎉 
<img src="https://media2.giphy.com/media/G7lfJRrvdhtxK8OVGy/giphy.gif"/>

## Highlights ✨✨
- Followed Gitflow ✅
- Great working on the functionality 🔥🚀🎉
- Descriptive PR ✅
- Professional README ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-14 02:00 UTC, Reem-lab commented on schema.sql
> +    species VARCHAR(100)
- [ OPTIONAL ] I think this is not the right way to add a colmun you should use the alter command so you can add a column to an existed table so kindly use the alter command for adding a new column. ✅🙏🏻

2022-12-14 02:39 UTC, merged